-- Tabela 01 EFD-Reinf – Naturezas de rendimento (seed ampliado)
-- INSERT IGNORE para não sobrescrever customizações
INSERT IGNORE INTO naturezas_rendimento (codigo, descricao, aplicavel_pf, aplicavel_pj, grupo, ativo, tabela_origem) VALUES
('10001', 'Rendimento decorrente do trabalho com vínculo empregatício', 1, 0, 'Trabalho', 1, '01'),
('10002', 'Rendimento decorrente do trabalho sem vínculo empregatício', 1, 0, 'Trabalho', 1, '01'),
('10003', 'Rendimento decorrente do trabalho pago a trabalhador avulso', 1, 0, 'Trabalho', 1, '01'),
('10004', 'Participação nos lucros ou resultados (PLR)', 1, 0, 'Trabalho', 1, '01'),
('10005', 'Benefício de Regime Próprio de Previdência Social', 1, 0, 'Trabalho', 1, '01'),
('10006', 'Benefício do Regime Geral de Previdência Social', 1, 0, 'Trabalho', 1, '01'),
('10007', 'Rendimentos relativos a prestação de serviços de Transporte Rodoviário Internacional de Carga, Auferidos por Transportador Autônomo Pessoa Física, Residente na República do Paraguai, considerado como Sociedade Unipessoal nesse País', 1, 0, 'Trabalho', 1, '01'),
('10008', 'Honorários advocatícios de sucumbência recebidos pelos advogados e procuradores públicos de que trata o art. 27 da Lei nº 13.327', 1, 0, 'Trabalho', 1, '01'),
('10009', 'Auxílio moradia', 1, 0, 'Trabalho', 1, '01'),
('10010', 'Bolsa ao médico residente', 1, 0, 'Trabalho', 1, '01'),
('11001', 'Decorrente de Decisão da Justiça do Trabalho', 1, 1, 'Decisão judicial', 1, '01'),
('11002', 'Decorrente de Decisão da Justiça Federal', 1, 1, 'Decisão judicial', 1, '01'),
('11003', 'Decorrente de Decisão da Justiça dos Estados/Distrito Federal', 1, 1, 'Decisão judicial', 1, '01'),
('11004', 'Responsabilidade Civil - juros e indenizações por lucros cessantes, inclusive astreinte', 1, 1, 'Decisão judicial', 1, '01'),
('11005', 'Decisão Judicial – Importâncias pagas a título de indenizações por danos morais, decorrentes de sentença judicial.', 1, 1, 'Decisão judicial', 1, '01'),
('12006', 'Resgate de Fundo de Aposentadoria Programada Individual (Fapi)- Optante pela Tributação Exclusiva', 1, 1, 'Capital', 1, '01'),
('12007', 'Resgate de Planos de Seguro de Vida com Cláusula de Cobertura por Sobrevivência- Optante pela Tributação Exclusiva', 1, 1, 'Capital', 1, '01'),
('12008', 'Resgate de Planos de Seguro de Vida com Cláusula de Cobertura por Sobrevivência - Não Optante pela Tributação Exclusiva', 1, 1, 'Capital', 1, '01'),
('12009', 'Benefício de Previdência Complementar - Modalidade Contribuição Definida/Variável - Não Optante pela Tributação Exclusiva', 1, 1, 'Capital', 1, '01'),
('12010', 'Benefício de Fundo de Aposentadoria Programada Individual (Fapi)- Não Optante pela Tributação Exclusiva', 1, 1, 'Capital', 1, '01'),
('12011', 'Benefício de Previdência Complementar - Modalidade Benefício Definido - Não Optante pela Tributação Exclusiva', 1, 1, 'Capital', 1, '01'),
('12012', 'Benefício de Previdência Complementar - Modalidade Contribuição Definida/Variável - Optante pela Tributação Exclusiva', 1, 1, 'Capital', 1, '01'),
('12013', 'Benefício de Fundo de Aposentadoria Programada Individual (Fapi)- Optante pela Tributação Exclusiva', 1, 1, 'Capital', 1, '01'),
('12014', 'Benefício de Planos de Seguro de Vida com Cláusula de Cobertura por Sobrevivência- Optante pela Tributação Exclusiva', 1, 1, 'Capital', 1, '01'),
('12015', 'Benefício de Planos de Seguro de Vida com Cláusula de Cobertura por Sobrevivência - Não Optante pela Tributação Exclusiva', 1, 1, 'Capital', 1, '01'),
('12016', 'Juros sobre o Capital Próprio', 1, 1, 'Capital', 1, '01'),
('12017', 'Rendimento de Aplicações Financeiras de Renda Fixa, decorrentes de alienação, liquidação (total ou parcial), resgate, cessão ou repactuação do título ou aplicação', 1, 1, 'Capital', 1, '01'),
('12018', 'Rendimentos auferidos pela entrega de recursos à pessoa jurídica, sob qualquer forma e a qualquer título, independentemente de ser ou não a fonte pagadora instituição autorizada a funcionar pelo Banco Central', 1, 1, 'Capital', 1, '01'),
('12019', 'Rendimentos predeterminados obtidos em operações conjugadas realizadas: nos mercados de opções de compra e venda em bolsas de valores, de mercadorias e de futuros (box); no mercado a termo nas bolsas de valores, de mercadorias e de futuros,', 1, 1, 'Capital', 1, '01'),
('12020', 'Rendimentos obtidos nas operações de transferência de dívidas realizadas com instituição financeira e outras instituições autorizadas a funcionar pelo Banco Central do Brasil', 1, 1, 'Capital', 1, '01'),
('12021', 'Rendimentos periódicos produzidos por título ou aplicação, bem como qualquer remuneração adicional aos rendimentos prefixados', 1, 1, 'Capital', 1, '01'),
('12022', 'Rendimentos auferidos nas operações de mútuo de recursos financeiros entre pessoa física e pessoa jurídica e entre pessoas jurídicas, inclusive controladoras, controladas, coligadas e interligadas', 1, 1, 'Capital', 1, '01'),
('12023', 'Rendimentos auferidos em operações de adiantamento sobre contratos de câmbio de exportação, não sacado (trava de câmbio), bem como operações com export notes, com debêntures, com depósitos voluntários para garantia de instância e com depósi', 1, 1, 'Capital', 1, '01'),
('12024', 'Rendimentos obtidos nas operações de mútuo e de compra vinculada à revenda tendo por objeto ouro, ativo financeiro', 1, 1, 'Capital', 1, '01'),
('12025', 'Rendimentos auferidos em contas de depósitos de poupança', 1, 1, 'Capital', 1, '01'),
('12026', 'Rendimentos auferidos sobre juros produzidos por letras hipotecárias', 1, 1, 'Capital', 1, '01'),
('12040', 'Rendimentos e ganhos de capital distribuídos pelo Fundo de Investimento Cultural e Artístico (Ficart)', 1, 1, 'Capital', 1, '01'),
('12050', 'Rendimento decorrente de Operação realizada em mercados de liquidação futura fora de bolsa', 1, 1, 'Capital', 1, '01'),
('13015', 'Rendimentos de Direito de Conjuntos Industriais e Invenções', 1, 1, 'Direitos', 1, '01'),
('14007', 'Prêmios distribuídos, em dinheiro, obtido mediante sorteios de jogos de bingo permanente ou eventual', 1, 1, 'Prêmios/capitalização', 1, '01'),
('14099', 'Demais Benefícios Líquidos decorrentes de título de capitalização', 1, 1, 'Prêmios/capitalização', 1, '01'),
('15001', 'Importâncias pagas ou creditadas a cooperativas de trabalho relativas a serviços pessoais que lhes forem prestados por associados destas ou colocados à disposição', 0, 1, 'Serviços PJ', 1, '01'),
('15002', 'Importâncias pagas ou creditadas a associações de profissionais ou assemelhadas, relativas a serviços pessoais que lhes forem prestados por associados destas ou colocados à disposição', 0, 1, 'Serviços PJ', 1, '01'),
('15003', 'Remuneração de Serviços de administração de bens ou negócios em geral, exceto consórcios ou fundos mútuos para aquisição de bens', 0, 1, 'Serviços PJ', 1, '01'),
('15004', 'Remuneração de Serviços de', 0, 1, 'Serviços PJ', 1, '01'),
('15005', 'Remuneração de Serviços de análise clínica laboratorial', 0, 1, 'Serviços PJ', 1, '01'),
('15006', 'Remuneração de Serviços de análises técnicas', 0, 1, 'Serviços PJ', 1, '01'),
('15007', 'Remuneração de Serviços de arquitetura', 0, 1, 'Serviços PJ', 1, '01'),
('15008', 'Remuneração de Serviços de assessoria e consultoria técnica, exceto serviço de assistência técnica prestado a terceiros e concernente a ramo de indústria ou comércio explorado pelo prestador do serviço;', 0, 1, 'Serviços PJ', 1, '01'),
('15009', 'Remuneração de Serviços de assistência social;', 0, 1, 'Serviços PJ', 1, '01'),
('15010', 'Remuneração de Serviços de auditoria;', 0, 1, 'Serviços PJ', 1, '01'),
('15011', 'Remuneração de Serviços de avaliação e perícia;', 0, 1, 'Serviços PJ', 1, '01'),
('15012', 'Remuneração de Serviços de', 0, 1, 'Serviços PJ', 1, '01'),
('15013', 'Remuneração de Serviços de cálculo em geral', 0, 1, 'Serviços PJ', 1, '01'),
('15014', 'Remuneração de Serviços de consultoria', 0, 1, 'Serviços PJ', 1, '01'),
('15015', 'Remuneração de Serviços de contabilidade', 0, 1, 'Serviços PJ', 1, '01'),
('15016', 'Remuneração de Serviços de', 0, 1, 'Serviços PJ', 1, '01'),
('15017', 'Remuneração de Serviços de economia', 0, 1, 'Serviços PJ', 1, '01'),
('15018', 'Remuneração de Serviços de', 0, 1, 'Serviços PJ', 1, '01'),
('15019', 'Remuneração de Serviços de engenharia, exceto construção de estradas, pontes, prédios e obras assemelhadas', 0, 1, 'Serviços PJ', 1, '01'),
('15020', 'Remuneração de Serviços de ensino e treinamento', 0, 1, 'Serviços PJ', 1, '01'),
('15021', 'Remuneração de Serviços de', 0, 1, 'Serviços PJ', 1, '01'),
('15022', 'Remuneração de Serviços de fisioterapia', 0, 1, 'Serviços PJ', 1, '01'),
('15023', 'Remuneração de Serviços de', 0, 1, 'Serviços PJ', 1, '01'),
('15024', 'Remuneração de Serviços de geologia', 0, 1, 'Serviços PJ', 1, '01'),
('15025', 'Remuneração de Serviços de leilão', 0, 1, 'Serviços PJ', 1, '01'),
('15026', 'Remuneração de Serviços de medicina, exceto aquela prestada por ambulatório, banco de sangue, casa de saúde, casa de recuperação ou repouso sob orientação médica, hospital e pronto-socorro', 0, 1, 'Serviços PJ', 1, '01'),
('15027', 'Remuneração de Serviços de nutricionismo e dietética', 0, 1, 'Serviços PJ', 1, '01'),
('15028', 'Remuneração de Serviços de odontologia', 0, 1, 'Serviços PJ', 1, '01'),
('15029', 'Remuneração de Serviços de organização de feiras de amostras, congressos, seminários, simpósios e congêneres', 0, 1, 'Serviços PJ', 1, '01'),
('15030', 'Remuneração de Serviços de pesquisa em geral', 0, 1, 'Serviços PJ', 1, '01'),
('15031', 'Remuneração de Serviços de planejamento', 0, 1, 'Serviços PJ', 1, '01'),
('15032', 'Remuneração de Serviços de programação', 0, 1, 'Serviços PJ', 1, '01'),
('15033', 'Remuneração de Serviços de prótese', 0, 1, 'Serviços PJ', 1, '01'),
('15034', 'Remuneração de Serviços de', 0, 1, 'Serviços PJ', 1, '01'),
('15035', 'Remuneração de Serviços de', 0, 1, 'Serviços PJ', 1, '01'),
('15036', 'Remuneração de Serviços de', 0, 1, 'Serviços PJ', 1, '01'),
('15037', 'Remuneração de Serviços de relações públicas', 0, 1, 'Serviços PJ', 1, '01'),
('15038', 'Remuneração de Serviços de serviço de despachante', 0, 1, 'Serviços PJ', 1, '01'),
('15039', 'Remuneração de Serviços de', 0, 1, 'Serviços PJ', 1, '01'),
('15040', 'Remuneração de Serviços de tradução ou interpretação comercial', 0, 1, 'Serviços PJ', 1, '01'),
('15041', 'Remuneração de Serviços de urbanismo', 0, 1, 'Serviços PJ', 1, '01'),
('15042', 'Remuneração de Serviços de veterinária', 0, 1, 'Serviços PJ', 1, '01'),
('15043', 'Remuneração de Serviços de Limpeza', 0, 1, 'Serviços PJ', 1, '01'),
('15044', 'Remuneração de Serviços de Conservação/ Manutenção, exceto reformas e obras assemelhadas', 0, 1, 'Serviços PJ', 1, '01'),
('15045', 'Remuneração de Serviços de Segurança/Vigilância/Transporte de valores', 0, 1, 'Serviços PJ', 1, '01'),
('15046', 'Remuneração de Serviços Locação de Mão de obra', 0, 1, 'Serviços PJ', 1, '01'),
('15047', 'Remuneração de Serviços de Assessoria Creditícia,', 0, 1, 'Serviços PJ', 1, '01'),
('17001', 'Alimentação', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17002', 'Energia elétrica', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17003', 'Serviços prestados com emprego de materiais', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17004', 'Construção Civil por empreitada com emprego de materiais', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17005', 'Serviços hospitalares de que trata o art. 30 da Instrução Normativa RFB nº 1.234, de 11 de janeiro de 2012', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17006', 'Transporte de cargas, exceto os relacionados na natureza de rendimento "17017"', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17007', 'Serviços de auxílio diagnóstico e terapia, patologia clínica, imagenologia, anatomia patológica e citopatológica, medicina nuclear e análises e patologias clínicas, exames por métodos gráficos, procedimentos endoscópicos, radioterapia, quim', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17008', 'Produtos farmacêuticos, de perfumaria, de toucador ou de higiene pessoal adquiridos de produtor, importador, distribuidor ou varejista, exceto os relacionados nas', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17009', 'Mercadorias e bens em geral', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17010', 'Gasolina, inclusive de aviação, óleo diesel, gás liquefeito de petróleo (GLP), combustíveis derivados de petróleo ou de gás natural, querosene de aviação (QAV), e demais produtos derivados de petróleo, adquiridos de refinarias de petróleo, ', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17011', 'Álcool etílico hidratado, inclusive para fins carburantes, adquirido diretamente de produtor, importador ou do distribuidor', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17012', 'Biodiesel adquirido de produtor ou importador', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17013', 'Gasolina, exceto gasolina de aviação, óleo diesel e gás liquefeito de petróleo (GLP), derivados de petróleo ou de gás natural e querosene de aviação adquiridos de distribuidores e comerciantes varejistas', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17014', 'Álcool etílico hidratado nacional, inclusive para fins carburantes adquirido de comerciante varejista', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17015', 'Biodiesel adquirido de distribuidores e comerciantes varejistas', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17016', 'Biodiesel adquirido de produtor detentor regular do selo “Combustível Social”, fabricado a partir de mamona ou fruto, caroço ou amêndoa de palma produzidos nas regiões norte e nordeste e no semiárido, por agricultor familiar enquadrado no P', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17017', 'Transporte internacional de cargas efetuado por empresas nacionais', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17018', 'Estaleiros navais brasileiros nas atividades de Construção, conservação, modernização, conversão e reparo de embarcações pré-registradas ou registradas no REB', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17019', 'Produtos de perfumaria, de toucador e de higiene pessoal a que se refere o § 1º do art. 22 da Instrução Normativa RFB nº 1.234, de 2012, adquiridos de distribuidores e de comerciantes varejistas', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17020', 'Produtos a que se refere o § 2º do art. 22 da Instrução Normativa RFB nº 1.234, de 2012', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17021', 'Produtos de que tratam as alíneas “c” a “k” do inciso I do art. 5º da Instrução Normativa RFB nº 1.234, de 2012', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17022', 'Outros produtos ou serviços beneficiados com isenção, não incidência ou alíquotas zero da Cofins e da Contribuição para o PIS/Pasep, observado o disposto no § 5º do art. 2º da Instrução Normativa RFB nº 1.234, de 2012', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17023', 'Passagens aéreas, rodoviárias e demais serviços de transporte de passageiros, inclusive, tarifa de embarque, exceto transporte internacional de passageiros, efetuado por empresas nacionais', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17024', 'Transporte internacional de passageiros efetuado por empresas nacionais', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17025', 'Serviços prestados por associações profissionais ou assemelhadas e cooperativas', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17026', 'Serviços prestados por bancos comerciais, bancos de investimento, bancos de desenvolvimento, caixas econômicas, sociedades de crédito, financiamento e investimento, sociedades de crédito imobiliário, e câmbio, distribuidoras de títulos e va', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17027', 'Seguro Saúde', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17028', 'Serviços de abastecimento de água', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17029', 'Telefone', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17030', 'Correio e telégrafos', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17031', 'Vigilância', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17032', 'Limpeza', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17033', 'Locação de mão de obra', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17034', 'Intermediação de negócios;', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17035', 'Administração, locação ou cessão de bens imóveis, móveis e direitos de qualquer natureza', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17036', 'Factoring', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17037', 'Plano de saúde humano, veterinário ou odontológico com valores fixos por servidor, por empregado ou por animal', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17038', 'Pagamento efetuado a sociedade cooperativa pelo fornecimento de bens, conforme art. 24, da IN 1234/12.', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17039', 'Pagamento a Cooperativa de produção, em relação aos atos decorrentes da comercialização ou da industrialização de produtos de seus associados, excetuado o previsto no §§ 1º e 2º do art. 25 da IN 1.234/12', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17040', 'Serviços prestados por associações profissionais ou assemelhadas e cooperativas que envolver parcela de serviços fornecidos por terceiros não cooperados ou não associados, contratados ou conveniados, para cumprimento de contratos – Serviços', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17041', 'Serviços prestados por associações profissionais ou assemelhadas e cooperativas que envolver parcela de serviços fornecidos por terceiros não cooperados ou não associados, contratados ou conveniados, para cumprimento de contratos - Demais s', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17042', 'Pagamentos efetuados às associações e às cooperativas de médicos e de odontólogos, relativamente às importâncias recebidas a título de comissão, taxa de administração ou de adesão ao plano', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17043', 'Pagamento efetuado a sociedade cooperativa de produção, em relação aos atos decorrentes da comercialização ou de industrialização, pelas cooperativas agropecuárias e de pesca, de produtos adquiridos de não associados, agricultores, pecuaris', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17044', 'Pagamento referente a aluguel de imóvel quando efetuado à entidade aberta de previdência complementar sem fins lucrativos, de que trata o art 34, § 2º da IN 1.234/2012.', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17045', 'Serviços prestados por cooperativas de radiotaxi, bem como àquelas cujos cooperados se dediquem a serviços relacionados a atividades culturais e demais', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17046', 'Pagamento efetuado na aquisição de bem imóvel, quando o vendedor for pessoa jurídica que exerce a atividade de compra e venda de imóveis, ou quando se tratar de imóveis adquiridos de entidades abertas de previdência complementar com fins lu', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17047', 'Pagamento efetuado na aquisição de bem imóvel adquirido pertencente ao ativo não circulante da empresa vendedora, conforme art. 23, inc II da IN RFB 1234/2012.', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17048', 'Pagamento efetuado na aquisição de bem imóvel adquirido de entidade aberta de previdência complementar sem fins lucrativos, conforme art. 23, inc III, da IN RFB 1234/2012.', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17049', 'Propaganda e Publicidade, em desconformidade ao art 16 da IN RFB 1234/2012, referente ao § 4º do citado artigo.', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17050', 'Propaganda e Publicidade, em conformidade ao art 16 da IN RFB 1234/2012, referente ao § 4º do citado artigo.', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('17099', 'Demais serviços', 0, 1, 'Alimentação/outros PJ', 1, '01'),
('18001', 'Fornecimento de bens, nos termos do art. 33 da Lei nº 10.833, de 2003', 1, 1, 'Exterior', 1, '01'),
('18002', 'Prestação de serviços em geral, nos termos do art. 33 da Lei nº 10.833, de 2003', 1, 1, 'Exterior', 1, '01'),
('18003', 'Transporte internacional de cargas ou de passageiros efetuados por empresas nacionais, aos estaleiros navais brasileiros e na aquisição de produtos isentos ou com Alíquota zero da Cofins e Pis/Pasep, conforme art. 4º, da IN SRF nº 475 de 20', 1, 1, 'Exterior', 1, '01'),
('18004', 'Pagamentos efetuados às cooperativas, em relação aos atos cooperativos, conforme art. 5º, da IN SRF nº 475 de 2004.', 1, 1, 'Exterior', 1, '01'),
('18005', 'Aquisição de imóvel pertencente a ativo permanente da empresa vendedora, conforme art. 19, II, da IN SRF nº 475 de 2004.', 1, 1, 'Exterior', 1, '01'),
('18006', 'Pagamentos efetuados às sociedades cooperativas, pelo fornecimento de bens ou serviços, conforme art. 24, II, da IN SRF nº 475 de 2004.', 1, 1, 'Exterior', 1, '01'),
('18007', 'Pagamentos efetuados à sociedade cooperativa de produção, em relação aos atos decorrentes da comercialização ou industrialização de produtos de seus associados, conforme art. 25, da IN SRF nº 475 de 2004.', 1, 1, 'Exterior', 1, '01'),
('18008', 'Pagamentos efetuados às cooperativas de trabalho, pela prestação de serviços pessoais prestados pelos cooperados, nos termos do art. 26, da IN SRF nº 475 de 2004.', 1, 1, 'Exterior', 1, '01');

-- Ajusta flags PF/PJ nos grupos principais
UPDATE naturezas_rendimento SET aplicavel_pf=1, aplicavel_pj=0, grupo='Trabalho' WHERE codigo BETWEEN '10001' AND '10099';
UPDATE naturezas_rendimento SET aplicavel_pf=1, aplicavel_pj=1, grupo='Decisão judicial' WHERE codigo BETWEEN '11001' AND '11099';
UPDATE naturezas_rendimento SET aplicavel_pf=0, aplicavel_pj=1, grupo='Serviços PJ' WHERE codigo BETWEEN '15001' AND '15999';
UPDATE naturezas_rendimento SET aplicavel_pf=0, aplicavel_pj=1, grupo='Alimentação/outros PJ' WHERE codigo BETWEEN '17001' AND '17999';
UPDATE naturezas_rendimento SET aplicavel_pf=0, aplicavel_pj=1, grupo='Retenção no recebimento' WHERE codigo BETWEEN '20001' AND '20999';
